include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = WifiTriggerPrefs

WifiTriggerPrefs_FILES = WifiTriggerRootListController.m
WifiTriggerPrefs_FRAMEWORKS = UIKit
WifiTriggerPrefs_PRIVATE_FRAMEWORKS = Preferences
WifiTriggerPrefs_INSTALL_PATH = /Library/PreferenceBundles
WifiTriggerPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk